# Generated by Django 5.1.4 on 2025-01-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='twitter_post_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
